### ISSUE TITLE
Mangler angivelse af `aca-fmt-34/35/36` i `custom_signatures.yml`?

### ISSUE THREAD

**Issue by ValdemarOtte** [aarhusstadsarkiv/reference-files#149]
Ved ikke om det er mig, som har misforstået hvordan strukturen i `reference-files` virker.

Men mangler vi ikke at give en `bof` og/eller `eof` til `aca-fmt-34/35/36` i `custom_signatures.yml`? De står nemlig ikke deri. De er kun i `fileformats.yml`.

Uddrag af `fileformats.yml`:
```
aca-fmt/34:
  name: Generic ZIP container
  action: ignore
  ignore:
    reason: File uses a generic ZIP container that should not be unpacked and cannot be opened
    template: not-preservable
aca-fmt/35:
  name: Generic CAD Drawing
  action: convert
  convert:
    tool: cad
    output: dxf
aca-fmt/36:
  name: XMind Mindmap
  action: convert
  convert:
    tool: zipfile
    output: "-"
    options:
      path: Thumbnails/thumbnail.png
```
